models: 
  - name: dim_movies
    description: Dimension table for the cleaned movie metadata
    columns:
      - name: movie_id
        description:  Primary key for r_movies
        tests:
          - not_null
          - unique
      - name: movie_title
        description: Hold movie title info
        tests:
          - not_null
      - name: GENRES_ARRAY
        description: Array form of generes
        tests:
          - not_null
      - name: genres
        description: raw string form of genere
        tests:
          - not_null

  - name: dim_users
    description: Dimension table for the cleaned users metadata
    columns:
      - name: user_id
        description:  Primary key for r_movies
        tests:
          - not_null
  
  - name: dim_genome_tags
    description: Dimension table dimension genome tags
    columns:
      - name: tag_id
        description:  Primary key for tags
        tests:
          - not_null
      - name: tag_name
        description:  Tag name for the tag tag_name

     