version: 2

sources:
  - name: netflix
    schema: raw
    tables:
      - name: r_movies
        identifier: raw_movies
      - name: r_genome_scores
        identifier: RAW_GENOME_SCORES
      - name: r_links
        identifier: raw_links
      - name: r_ratings
        identifier: RAW_RATINGS
      - name: r_genome_tags
        identifier: RAW_GENOME_TAGS
      - name: r_tags
        identifier: RAW_TAGS